name: Deploy to https://bookgames.angelator312.top/
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
    steps:
      - name: Trigger deploy
        shell: bash
        run: curl "$DEPLOY_URL"
